<?php
/**
 * MediaWiki LocalSettings for E2E and integration testing.
 * Used by the Docker Compose setup. Not for production.
 */

# Base settings (generated by install.php, then overridden here).
$wgSitename = 'ImproveSearch Test Wiki';
$wgServer = 'http://localhost:8080';
$wgScriptPath = '';
$wgArticlePath = '/wiki/$1';

# MariaDB (created by install.php). The extension's engine extends
# SearchMySQL, so no other backend exercises it.
$wgDBtype = 'mysql';
$wgDBserver = 'database';
$wgDBname = 'testwiki';
$wgDBuser = 'wikiuser';
$wgDBpassword = 'wikipassword';

# Disable object caching for test predictability.
$wgMainCacheType = CACHE_NONE;
$wgSessionCacheType = CACHE_NONE;
$wgMessageCacheType = CACHE_NONE;
$wgJobTypeConf['default'] = [ 'class' => 'JobQueueMemory' ];
$wgObjectCaches['default'] = [ 'class' => HashBagOStuff::class ];

# Use file-based localisation cache so load.php does not query the database.
$wgCacheDirectory = '/tmp/mw-cache';
$wgLocalisationCacheConf['store'] = 'file';
$wgLocalisationCacheConf['manualRecache'] = false;

# Secret key (test-only, not sensitive).
$wgSecretKey = 'e2e-test-secret-key-not-for-production-0123456789abcdef';
$wgUpgradeKey = 'e2e-test-upgrade-key';

# Disable email.
$wgEnableEmail = false;

# Load Vector skin (default in MW 1.44).
wfLoadSkin( 'Vector' );

# Load ImproveSearch. Every switch is on by default; the e2e suite asserts
# the default behaviour.
wfLoadExtension( 'ImproveSearch' );

# One template whose parameter values stay in the index, so the "address in
# a template parameter" case has something to find.
$wgImproveSearchKeepTemplateParams = [ 'Address' => [ 'street', 'number' ] ];

# Debug (useful when tests fail).
$wgShowDBErrorBacktrace = true;
$wgShowExceptionDetails = true;
